[package]
name = "cryptopals-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.2"
hex = "0.4.3"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
